### PR TITLE
Add Restrict Navigation plugin

### PR DESCRIPTION
**Pull request by marlara**
A new plugin to set some restriction in the backend of OJS 3.

### CODE REVIEW

**Comment by asmecher** [comment]
@marlara, the tests are failing because it appears that the plugin isn't packaged in the right form:
> Error: Validation of tar file failed: There should be only one folder in the root of the extracted file named "restrictNavigation"

See our plugin build documentation for how to package a plugin:

https://docs.pkp.sfu.ca/dev/plugin-guide/en/release#build-and-package-your-plugin

**Comment by asmecher** [comment]
Hi @marlara! For this plugin to be effective, you'd need to block access to the APIs that are used to save settings, not just the UI to present the forms. If it's OK, I'd rather that change was implemented before we added the plugin to the Plugin Gallery. A malicious user could still access the API directly to change settings, even though it would appear that the interface wasn't available to them.

**Comment by marlara** [comment]
Hi @asmecher, ok no problem. Could you give me some documentation about APIs? I will check, but I want to be sure to have all of it.

**Comment by asmecher** [comment]
Closing as out of date; please re-open if you'd like one of us to take a look.

**Pull request closed without merging**
