### PR TITLE
Change term used for "plugin" in spanish descriptions

### PR DESCRIPTION
**Pull request by richardLepidus**
Change "complemento" for "módulo" to better fit the es_ES community dialect 

Affected plugins (maintained by Lepidus): 
- authorsHistory
- pluginUpdateNotification
- plaudit

Signed-off-by: Richard <richard@lepidus.com.br>
Signed-off-by: Laís <lais@lepidus.com.br>

### CODE REVIEW

**Comment by asmecher** [comment]
Merged, thanks, @richardLepidus! But in the future, could you use Weblate for translation changes? https://translate.pkp.sfu.ca/

**Comment by richardLepidus** [comment]
Sure, thanks, @asmecher!

**Comment by iudizm** [comment]
Sorry @asmecher, but it does not seem possible to edit the gallery description of a plugin through Weblate.
How can we do this?

Maybe you are referring to the plugin translations? If so, is there a way to include our plugins to Weblate so that the locales can be translated by the community as well?

**Comment by asmecher** [comment]
Oh! Yes, you're absolutely right. I made that comment on auto-pilot.

**Pull request merged**
