### PR TITLE
Update Shariff plugin

### PR DESCRIPTION
**Pull request by ronste**
New feature added to select URL to share (see [https://github.com/ojsde/shariff/issues/37](https://github.com/ojsde/shariff/issues/37))

### CODE REVIEW

**Comment by asmecher** [comment]
@ronste, it looks like the MD5 hash is wrong; can you check it?

**Comment by ronste** [comment]
> @ronste, it looks like the MD5 hash is wrong; can you check it?

I double checked the MD5, its correct. But I remeber we had this issue last time alreay: https://github.com/pkp/plugin-gallery/pull/230#discussion_r1340345233

I looked into the build: https://app.travis-ci.com/github/pkp/plugin-gallery/builds/268461054

It again didn't get the expected MD5 correct:

```
Package url: https://github.com/ojsde/shariff/releases/download/v3_4_0-2/shariff-3_4_0-2.tar.gz. Expected MD5: ********************************

The MD5 of the downloaded is incorrect. Expected ********************************, Actual 58d648c41009b2e912cf788e78bd59a7
``` 

But this time I only submitted one release package ... Should we discuss version numbers again ???

**Comment by asmecher** [comment]
@ronste, actually, I think the problem is just the capitalization in the alpha parts of the md5sum -- we're doing a string test so they don't match. Could you change out capitals for lower case? Thanks/sorry!

**Comment by ronste** [comment]
@asmecher , done. Seems it did the trick!

**Comment by asmecher** [comment]
Merged, thanks!

**Pull request merged**
