### PR TITLE
Add Web of Science Reviewer Recognition Service plugin for OJS 3.1, update for OJS 3.4

### PR DESCRIPTION
**Pull request by Alex-nz**
- Add Web of Science Reviewer Recognition Service plugin for OJS 3.1 into the plugin gallery.
- Update version of the plugin for OJS 3.4

### CODE REVIEW

**Comment by Alex-nz** [comment]
hi team, can someone please code review this PR to add releases for the WoS RRS plugin. Previous PR for this plugin was reviewed by @bozana https://github.com/pkp/plugin-gallery/pull/301

**Comment by bozana** [comment]
Hi @Alex-nz, 
For your version 1.3.1.0 I would suggest that you add addRoleAssignment, function authorize, and the check `if($request->getContext()->getId() != $journalId) {` as in the version I reviewed before.
I also think that you should leave the version 1.3.4.1 here in the plugins.xml, because someone could already be using it, and to just add the new 1.3.4.2 version. What is actually the change from 1.3.4.1 and 1.3.4.2?
Thanks a lot!

**Comment by Alex-nz** [comment]
Thanks for the review @bozana. 
> For your version 1.3.1.0 I would suggest that you add addRoleAssignment, function authorize, and the check `if($request->getContext()->getId() != $journalId) {` as in the version I reviewed before.

Is this critical for the approval? It's an older version of the plugin and we were hoping to simply re-brand it from Publons, without investing much time in re-writing.

> I also think that you should leave the version 1.3.4.1 here in the plugins.xml, because someone could already be using it, and to just add the new 1.3.4.2 version. What is actually the change from 1.3.4.1 and 1.3.4.2?

Ok, I wasn't sure of the process here and actually was wondering if that's going to be a better way. I'll update that.

**Comment by Alex-nz** [comment]
I'll update the PR tomorrow then, thank you

**Comment by Alex-nz** [comment]
@bozana this is ready for re-review, please.

**Pull request merged**
