### PR TITLE
Funding plugin for 3.3

### PR DESCRIPTION
**Pull request by ajnyga**
Fixed the crossref issue...

### CODE REVIEW

**Comment by ajnyga** [comment]
@asmecher this is the fix release for the Funding plugin

**Comment by asmecher** [comment]
Thanks, @ajnyga!

**Comment by asmecher** [comment]
@ajnyga, it looks like this plugin package was removed from the Github Releases area; it's best not to do that, or it'll break our CI testing for the Plugin Gallery. I'll remove this (and one or two others) that have disappeared.

**Comment by ronste** [comment]
Hi @ajnyga ,

may I ask what is the progress here for 3.3 and 3.4? We have customers who want to update the plugin via the plugin gallery and I promised them it would be availble soon. (Yes, the latter is my fault ;-))

**Comment by ajnyga** [comment]
@asmecher sorry for messing up the old releases and good to know (which was of course apparent) that deleting them in these cases is not a good idea.

@ronste the new releases are ready and did a new pr to be merged here https://github.com/pkp/plugin-gallery/pull/321

**Pull request merged**
