### PR TITLE
update theme plugins for 3.4

### PR DESCRIPTION
**Pull request by kaitlinnewson**
Update theme plugins:
- Classic
- Health Sciences
- Immersion
- Pragma

### CODE REVIEW

**Comment by kaitlinnewson** [comment]
@asmecher Ready for a review

**Comment by asmecher** [comment]
Thanks, @kaitlinnewson! The plugin validation tool only expects one new plugin per PR (another thing that could be improved), so it only validated classic. Could you split this into several PRs, one per plugin?

Also, I suspect it's only cosmetic, but I do see a bunch of warnings in the extraction part of the test:
```
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
```
This appears to be due to differences between BST tar and GNU tar; it might be worth using GNU tar on your system to build plugins. On the extraction side, adding `--warning=no-unknown-keyword` seems to silence it, but I'd hate to start spreading that around everywhere in case it has knock-on effects.

**Comment by kaitlinnewson** [comment]
@asmecher new PRs created and I've recreated the release packages using GNU tar.

**Comment by asmecher** [comment]
All merged, thanks, @kaitlinnewson!

**Pull request closed without merging**
