### PR TITLE
Adds new version of Plaudit plugin to plugin gallery 

### PR DESCRIPTION
**Pull request by LaisLepidus**

### CODE REVIEW

**Comment by asmecher** [comment]
I see a few pushes have come through recently; is this ready to go?

**Comment by LaisLepidus** [comment]
We made one last change, if approved by Travis, we will not be making any further changes.

**Comment by LaisLepidus** [comment]
We take advantage that the Pull Request has not yet been approved for add a new version of the plugin that makes it mandatory to use the integration token.

**Comment by iudizm** [comment]
Made some updates in the latest version description to better explain the version improvements.

This is ready to go.

**Comment by asmecher** [comment]
Merged, thanks!

**Pull request merged**
