### PR TITLE
Added Sitesearch compatibility for 3.3

### PR DESCRIPTION
**Pull request by wopsononock**

### CODE REVIEW

**Comment by wopsononock** [comment]
I'll have to track down why the Travis check failed.

**Comment by wopsononock** [comment]
Fixed some whitespace issues, but still looking for the build failure.

**Comment by asmecher** [comment]
@wopsononock, I'm pretty sure that's a Travis glitch, but I've started a fresh build off `main` (which has previously passed testing) to see what happens: https://app.travis-ci.com/github/pkp/plugin-gallery/builds/249772248

**Comment by asmecher** [comment]
Yep, same problem. I've filed a ticket with Travis, but it's such a commonly-used configuration that I suspect it'll start working again long before I get a response on the ticket.

**Comment by asmecher** [comment]
@wopsononock, I got a quick response from the folks at Travis; they're probably going to continue debugging the distro we were using, but in the meantime suggested changing distros, which I've done. If you rebase from `main` it should be working again.

**Comment by asmecher** [comment]
@wopsononock, I got a quick response from the folks at Travis; they're probably going to continue debugging the distro we were using, but in the meantime suggested changing distros, which I've done. If you rebase from `main` it should be working again.

**Review by ctgraham — APPROVED** [review]

**Comment by asmecher** [comment]
Thanks, @ctgraham and @wopsononock!

**Pull request merged**
