### PR TITLE
Funding plugin for 3.4.0

### PR DESCRIPTION
**Pull request by ajnyga**

### CODE REVIEW

**Comment by asmecher** [comment]
Hi @ajnyga! Sorry for the delay in looking this over. Is there a reason you're replacing a previous build rather than adding a new one?

**Comment by ajnyga** [comment]
Oh, have not noticed. This. Really can not remember. Is that a problem?

**Comment by asmecher** [comment]
I don't think it'll cause problems, but I'd rather keep old entries in the gallery for the sake of knowing what was actually released to the community. Could you adjust this so that it's a new entry rather than a replacement?

**Comment by ajnyga** [comment]
I will do a new pr an close this

**Comment by ajnyga** [comment]
https://github.com/pkp/plugin-gallery/pull/260

**Pull request closed without merging**
