### PR TITLE
add entry <plugin category="generic" product="rqc">

### PR DESCRIPTION
**Pull request by prechelt**
My plugin for Review Quality Collector, which I have been developing since 2018, has finally reached a state where I'd like to look for some pilot users.

It needs automated tests eventually, but for today I have tested it well enough by hand.

### CODE REVIEW

**Comment by prechelt** [comment]
I should add that, embarassingly, reviewqualitycollector.org currently has an outdated SSL certificate.
My techfolks are working on it!

**Comment by asmecher** [comment]
Hi @prechelt! Congratulations on getting this ready for launch.

The `<compatibility>` elements need a small change; you should list all releases that are compatible specifically:
```xml
<version>3.3.0.0</version>
<version>3.3.0.1</version>
<version>3.3.0.2</version>
<version>3.3.0.3</version>
<version>3.3.0.4</version>
<version>3.3.0.5</version>
<version>3.3.0.6</version>
<version>3.3.0.7</version>
<version>3.3.0.8</version>
<version>3.3.0.9</version>
<version>3.3.0.10</version>
<version>~3.3.0.0</version>
```
Starting with `3.3.0-11`, we began supporting semantic versioning, so the last line will cover anything 3.3.0-11 and newer.

(These version numbers are parsed and used in listing plugins that are available and compatible within an OJS user's Plugin Gallery.)

**Comment by prechelt** [comment]
Hi @asmecher,

thank you! Done.

In the future, I'd prefer including all of **3.3.x** in the compatibility tags and reduce that if something incompatible turns up rather than always being late when a new third-digit version (3.3.1.x etc.) appears, so that the plugin is not immediately available to OJS early upgraders.  
Would that be OK with you?

BTW, I find the notation **3.3.0.x** (which also works) clearer than this curious **~3.3.0.0**.

**Comment by asmecher** [comment]
@prechelt, we won't ever release a 3.3.1, so you're safe to use `~3.3.0.0`. It's equivalent.

The `~` is a semver (Semantic Versioning) thing; see https://semver.org/ for information on the various kinds of wildcards.

I often use regular expressions etc. to change the plugin list, so selfishly, staying consistent with the other plugins in using `~3.3.0.0` rather than e.g. `~3.3.0` or `^3.3.0` will help me manage the plugin list!

**Comment by asmecher** [comment]
In any case -- merged, thanks!

**Pull request merged**
