### PR TITLE
Adds the first release of ARK PubId plugin to the gallery plugin

### PR DESCRIPTION
**Pull request by yasielpv**
Adds the first release of ARK PubId plugin to the gallery plugin.  The ARK plugin enables the assignation and management of ARK ID to issue, article and galley.

### CODE REVIEW

**Comment by asmecher** [comment]
@yasielpv, the plugin needs to be packaged a certain way in order for the Plugin Gallery to support it; that's why the CI testing is failing (https://travis-ci.com/github/pkp/plugin-gallery/builds/224696213). See: https://docs.pkp.sfu.ca/dev/plugin-guide/en/release#build-and-package-your-plugin

**Comment by yasielpv** [comment]
@asmecher Any update from this PR?

**Comment by asmecher** [comment]
@yasielpv, this looks great -- I didn't realize it was ready for review again. (Next time, after adding commits, please tag me with a reminder.) The only change I'd suggest is adding compatibility with 3.3.0-7; it should be compatible with anything that's also compatible with 3.3.0-6.

**Comment by yasielpv** [comment]
@asmecher Ready, I added the 3.3.0.7 compatibility as you suggested

**Comment by asmecher** [comment]
Thanks, @yasielpv! How far back did you test the <=3.1.x version? At a glance, I suspect it will not be compatible all the way back to 3.0. There were also a few significant changes at least between 3.1.1 and 3.1.2 (multilingual support for author names, for example).

**Comment by yasielpv** [comment]
@asmecher I tested it from version 3.1.2.1 to 3.3.0.6

**Comment by asmecher** [comment]
OK, thanks! I'd recommend removing the compatibility statements prior to 3.1.2-0, then; I don't think it's likely to work without modification (and our user community really should be upgrading to at least 3.1.2 anyway).

**Comment by yasielpv** [comment]
Thank you @asmecher, I follow your suggestions. Done!!!!

**Comment by carlosauthier** [comment]
Está aceptado el plug-in en America Latina lo esperamos con mucha ansiedad!

**Comment by asmecher** [comment]
Felicitaciones y gracias, @yasielpv y @carlosauthier! Esta entrado en el repositorio.

**Pull request merged**
