### PR TITLE
Update plugins.xml

### PR DESCRIPTION
**Pull request by trp89**
Updated the betterPassword plugin section to include a new release for OJS/OMP/OPS 3.4

### CODE REVIEW

**Review by ctgraham — CHANGES_REQUESTED** [review]
I think there is one more edit to betterPassword needed prior to release.

**Comment by asmecher** [comment]
@ctgraham, does this address your comment above?

**Comment by ctgraham** [comment]
Yes, [446c2dd](https://github.com/pkp/plugin-gallery/pull/259/commits/446c2dd027535d9d246e1c2c22968599e3efe1ff) is the corrected release.

**Comment by asmecher** [comment]
Merged, thanks!

**Pull request merged**
