### PR TITLE
material-v3_0_1

### PR DESCRIPTION
**Pull request by madi-nuralin**
This release upgrades Material to version [3.0.1.0](https://github.com/madi-nuralin/material/releases/tag/v3_0_1-0)

### CODE REVIEW

**Comment by madi-nuralin** [comment]
Hi @asmecher!
Could you please consider the mr?)
Thanks.

**Comment by asmecher** [comment]
@madi-nuralin, would you still like this to be considered?

**Comment by madi-nuralin** [comment]
Hi, 
I had problems with plugin's repository, so that I temporarily closed PR.
Now it seems to be ok.

**Comment by asmecher** [comment]
Thanks! I've merged the PR.

**Pull request merged**
