### PR TITLE
Toogle Required Metadata for OJS 3.4

### PR DESCRIPTION
**Pull request by lucasDevLepidus**
Adapt Toggle Required Metadata plugin for OJS 3.4

### CODE REVIEW

**Comment by asmecher** [comment]
Hi @lucasDevLepidus! Thanks for the contribution. Now that we support semantic versioning style versions for the compatibility indicators, could you make the adjustment described here? It'll help keep the plugin gallery shorter, plus we won't have to add new compatibility lines for each new release that comes out.

https://github.com/pkp/plugin-gallery/pull/214#issuecomment-1654501386

**Comment by lucasDevLepidus** [comment]
Hi @asmecher 

Thank you for the warning. [Added version style semantics to instance declaration](https://github.com/pkp/plugin-gallery/pull/215/commits/62d8e73d8b7a63ffb58f93e9a33f15276ebca94e)

**Comment by asmecher** [comment]
Sorry, one more change! The language code `es_ES` should be changed to `es`, and `en_US` should be removed. (The longer forms `es_ES` and `en_US` are only for 3.3.0 and older; going forward almost all locale codes are two-letter.)

**Comment by lucasDevLepidus** [comment]
Hi @asmecher 

[I made a commit correcting the translation keys of the descriptions](https://github.com/pkp/plugin-gallery/pull/215/commits/ea258d906c178113851075c400301e3224769d36).

**Comment by asmecher** [comment]
Merged -- thanks, @lucasDevLepidus!

**Pull request merged**
