### PR TITLE
Adds first release of SciELO Submissions Report

### PR DESCRIPTION
**Pull request by JhonathanLepidus**
We are releasing this plugin in the Plugin Gallery so it can be widely used by SciELO journals.

### CODE REVIEW

**Comment by asmecher** [comment]
@JhonathanLepidus, sorry for the trouble with the Travis tests -- but would it be possible to fix this before the plugin goes into the gallery?
https://github.com/lepidus/scieloSubmissionsReport/issues/1

**Comment by JhonathanLepidus** [comment]
@asmecher This will be no problem. In fact, thank you for awaring us of this problem.

**Comment by JhonathanLepidus** [comment]
@asmecher We fixed the problem and updated the release in this PR, so the better release goes to plugin gallery :)

**Comment by asmecher** [comment]
Merged -- thanks, @JhonathanLepidus!

**Comment by JhonathanLepidus** [comment]
@asmecher Thanks! We're really happy to make this plugin available!

**Pull request merged**
